import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, realpath } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { _electron as electron } from 'playwright';

const root = fileURLToPath(new URL('../', import.meta.url));
test('full desktop exposes unconfigured services and preserves local features across restart', { timeout: 90_000 }, async t => {
  const profile = await realpath(await mkdtemp(path.join(os.tmpdir(), 'community-desktop-')));
  let desktop;
  t.after(async () => { if (desktop) await desktop.close(); await rm(profile, { recursive: true, force: true }); });
  const launch = async () => {
    const env = { ...process.env, TXCHAT_COMMUNITY_PROFILE: profile, TXCHAT_COMMUNITY_NO_NATIVE: '1' };
    delete env.ELECTRON_RUN_AS_NODE;
    desktop = await electron.launch({ args: [root], env, chromiumSandbox: true });
    const page = await desktop.firstWindow();
    await page.getByTestId('setup.unavailable').waitFor();
    return page;
  };
  let page = await launch();
  const read = () => page.evaluate(() => window.txchat.read());
  const command = value => page.evaluate(value => window.txchat.command(value), value);
  const initial = await read();
  assert.equal(initial.product.stage, 'setup-unavailable');
  assert.equal(initial.product.environment.configured, false);
  assert.equal(initial.helper.status, 'stopped');
  assert.equal(initial.product.auth.signedIn, false);
  assert.equal(initial.product.auth.maskedPhone, null);
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  const preferences = await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().map(window => {
    const p = window.webContents.getLastWebPreferences();
    return { sandbox: p.sandbox, contextIsolation: p.contextIsolation, nodeIntegration: p.nodeIntegration, webSecurity: p.webSecurity };
  }));
  for (const p of preferences) assert.deepEqual(p, { sandbox: true, contextIsolation: true, nodeIntegration: false, webSecurity: true });
  assert.equal(preferences.length, 6);
  assert.equal(await page.evaluate(async () => { try { await window.txchat.command({ type: 'start', extra: true }); return false; } catch { return true; } }), true);
  await command({ type: 'preferences', language: 'en' });
  await page.getByRole('button', { name: 'View Login', exact: true }).click();
  assert.ok((await page.locator('body').innerText()).includes('service'));
  await command({ type: 'demo-enter' });
  await page.getByRole('button', { name: 'Local development', exact: false }).waitFor();
  assert.equal((await read()).product.stage, 'ready');
  assert.equal((await read()).product.auth.signedIn, false);
  assert.equal((await read()).product.auth.demo, true);
  await command({ type: 'product-page', page: 'dictionary' });
  await command({ type: 'dictionary-save', entries: [{ wrong: 'alpha', correct: 'beta', enabled: true }] });
  assert.deepEqual((await read()).product.dictionary.entries, [{ wrong: 'alpha', correct: 'beta', enabled: true }]);
  await command({ type: 'preferences', theme: 'dark' });
  assert.equal((await read()).product.preferences.theme, 'dark');
  await command({ type: 'product-page', page: 'membership' });
  await command({ type: 'billing-refresh' });
  assert.equal((await read()).product.billing.offer, null);
  await command({ type: 'product-page', page: 'custom-ai' });
  assert.equal((await read()).product.page, 'custom-ai');
  await command({ type: 'document-open', document: 'cloud' });
  assert.ok((await read()).product.document.blocks.some(block => block.text.includes('adapter')));
  await command({ type: 'document-close' });
  await command({ type: 'update-check' });
  const updatePage = desktop.windows().find(window => window.url().endsWith('#update'));
  assert.ok(updatePage);
  await updatePage.getByText('The update service is not configured or is unavailable.', { exact: false }).waitFor();
  assert.equal((await read()).product.update.visible, true);
  await updatePage.getByRole('button', { name: 'Close', exact: true }).last().click();
  assert.equal((await read()).product.update.visible, false);
  await desktop.close(); desktop = undefined;
  page = await launch();
  assert.equal((await read()).product.preferences.theme, 'dark');
  await command({ type: 'demo-enter' });
  await page.getByRole('button', { name: 'Local development', exact: false }).waitFor();
  assert.deepEqual((await read()).product.dictionary.entries, [{ wrong: 'alpha', correct: 'beta', enabled: true }]);
  assert.equal((await read()).helper.status, 'stopped');
});
