import { AUDIO_REASONS } from './native-audio';

// Only fixed classifications cross IPC; never expose raw provider messages.
export const DICTATION_FAILURE_CODES = [...AUDIO_REASONS,
  'TARGET_UNAVAILABLE', 'BILLING_QUOTA_EXHAUSTED', 'UPSTREAM_UNAVAILABLE', 'FINAL_TIMEOUT',
  'AUTH_REQUIRED', 'SESSION_REPLACED', 'SESSION_EXPIRED', 'ACCOUNT_DISABLED', 'TOO_MANY_REQUESTS',
  'PROTOCOL_ERROR', 'AUDIO_LIMIT_EXCEEDED', 'NETWORK_UNAVAILABLE', 'REQUEST_TIMEOUT',
  'CUSTOM_AI_INVALID_CONFIGURATION', 'CUSTOM_AI_AUTHENTICATION', 'CUSTOM_AI_RATE_LIMIT',
  'CUSTOM_AI_TIMEOUT', 'CUSTOM_AI_NETWORK', 'CUSTOM_AI_EMPTY_RESULT',
  'CUSTOM_AI_NOT_CONFIGURED', 'CUSTOM_AI_PERMISSION_OR_MODEL', 'CUSTOM_AI_INCOMPATIBLE_RESPONSE',
  'CUSTOM_AI_INVALID_REQUEST', 'CUSTOM_AI_RESPONSE_TOO_LARGE', 'CUSTOM_AI_AUDIO_SAMPLE',
  'CUSTOM_AI_INVALID_AUDIO', 'CUSTOM_AI_AUDIO_LIMIT', 'CUSTOM_AI_UNSUPPORTED_PROVIDER',
  'CUSTOM_AI_INVALID_RESPONSE', 'CUSTOM_AI_PROTOCOL_ERROR', 'DICTATION_FAILED',
] as const;
export type DictationFailureCode = typeof DICTATION_FAILURE_CODES[number];
export function dictationFailureCode(error: unknown): DictationFailureCode {
  const code = error instanceof Error ? error.message : '';
  if (['AUDIO_CONVERSION_FAILED', 'AUDIO_INVALID_STATE', 'AUDIO_OVERFLOW'].includes(code)) return 'AUDIO_INTERRUPTED';
  return DICTATION_FAILURE_CODES.includes(code as DictationFailureCode) ? code as DictationFailureCode : 'DICTATION_FAILED';
}
